name: myExample

on: 
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.3"
