name: Evaluate LaunchDarkly flags
on: push
jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: ld
        uses: launchdarkly/gha-flags@v0.1.0
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: test-feature-flag,stagging
      - name: If stagging
        if: fromJSON(steps.ld.outputs.test-feature-flag) == 'stagging'
        run: echo "It's stagging"
      - name: If QA
        if: fromJSON(steps.ld.outputs.test-feature-flag) == 'QA'
        run: echo "It's QA"
