name: Tag version2
on:
  push:
    branches:
      - stage
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: Krishnendu1987/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
