name: Create Tag

on:
  push:
    branches:
      - QA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.Access_Token }}"
        
