name: CI

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]
  workflow_dispatch:

jobs:
  scheduled_run:
    name: scheduled_run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag -a v${{ github.run_number }} -m "Auto-tagged by GitHub Actions"
          git push origin v${{ github.run_number }}
