name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: anothrNick/github-tag-action@1.61.0 
      with:
        GITHUB_TOKEN: "${{ secrets.Access_Token }}"
